### ISSUE TITLE
CLI Flags

### ISSUE THREAD

**Issue by sputnik27** [osiam/shell#18]
The `connect` and `login` commands could be substituted by command-line flags. This might make the shell easier and faster to use. Furthermore, the user could define aliases for different connections.

**Comment by sschum** [comment]
I thought about command aliases before and made an [issue](https://github.com/rainu/jsimpleshell/issues/83) for that.

**Comment by sputnik27** [comment]
What I was talking about are arguments for the program. Something like

`java -jar build/libs/shell-1.1-SNAPSHOT-all.jar --endpoint http://localhost:8080 --redirectUri http://localhost:5000/oauth2 --clientId example-client --clientSecret secret --username admin --password koala`

But I realize that passing passwords on the command line is not a very good idea. Maybe we could read from environment variables instead?

@sschum: What do you think where such features would be implemented best? In JSimpleShell or in the osiam shell? I think this is such a broad feature that every shell using JSS could potentially benefit from it.

**Comment by sputnik27** [comment]
Oh, I have another question about that issue. I was trying to do the `connect` and `login` with the provided information, but 

```
shell.processLine(String.format("connect %s %s %s %s",
	configuration.endpoint, configuration.redirectUri,
	configuration.clientId, configuration.clientSecret));
shell.processLine(String.format("login %s %s", configuration.username, configuration.password));
```

did not work. Did I get the purpose of `processLine()` wrong? Is it not able to process commands that are defined in the shell itself and not in JSS?

**Comment by sschum** [comment]
You could read variables from environment or add program arguments. But this is not a feature for JSS. Because the main-method of the osiam-shell has nothing to do with JSS.

If you want to execute commands programmaticaly it is better when you use the _command-pipeline_. The problem of __processLine()__ is that this command will execute directly in this instance of shell. But in your case "connect" will create a new subshell (a different instance of shell). So the command "connect" will be executed but a new subshell is open and wait for commands from the user. When the subshell is leaving the second __processLine__ will be executed.

The _command-pipeline_ will be forward to each subshells. For you case it is exactly what you need:
```
shell.getPipeline().append("connect ...");
shell.getPipeline().append("login ...");
shell.commandLoop();	//enter shell
```

For the program arguments you can read the args[] from main(), build your commands and pushing them into the pipeline before start the shell.
